// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgeeRzKoCzfdSZXzkQvZVUTSgpvo-C14k',
    appId: '1:917027323422:web:0cf831b7e821e93d10380f',
    messagingSenderId: '917027323422',
    projectId: 'auth-6c81a',
    authDomain: 'auth-6c81a.firebaseapp.com',
    storageBucket: 'auth-6c81a.appspot.com',
    measurementId: 'G-GR6KVW5J2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxU0SIaKO-fN4op8oZrwXUq8O1E4ctaAA',
    appId: '1:917027323422:android:312f87561589a79610380f',
    messagingSenderId: '917027323422',
    projectId: 'auth-6c81a',
    storageBucket: 'auth-6c81a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqS_gE53OM7_2vzJgLgXUAaF9q064msBs',
    appId: '1:917027323422:ios:e51896169983e67310380f',
    messagingSenderId: '917027323422',
    projectId: 'auth-6c81a',
    storageBucket: 'auth-6c81a.appspot.com',
    iosClientId: '917027323422-g9b9q34ajejjfhcojq17v9hi65u2gdj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqS_gE53OM7_2vzJgLgXUAaF9q064msBs',
    appId: '1:917027323422:ios:e51896169983e67310380f',
    messagingSenderId: '917027323422',
    projectId: 'auth-6c81a',
    storageBucket: 'auth-6c81a.appspot.com',
    iosClientId: '917027323422-g9b9q34ajejjfhcojq17v9hi65u2gdj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );
}
